### DISCUSSION TITLE
github-actions/

### DISCUSSION THREAD

**Discussion by giscus** [jaywcjlove/github-actions#5] [Ideas]
# github-actions/

测试 GitHub 工作流，一些比较特殊的玩儿法。

https://wangchujiang.com/github-actions/

**Comment by jaywcjlove** [comment]
忽略

```yml
'on':
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    # 忽略以下文件
    paths-ignore:
      - '**.md'
      - 'LICENSE'
```
